// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mod_network_nic_list;
mp_obj_list_t mp_sys_argv_obj;
mp_obj_list_t mp_sys_path_obj;
mp_obj_t dupterm_objs[(3)];
mp_obj_t pin_class_map_dict;
mp_obj_t pin_class_mapper;
mp_obj_t pyb_config_main;
mp_obj_t pyb_extint_callback[(23)];
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
mp_obj_t track_reloc_code_list;
mp_sched_item_t sched_queue[(8)];
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
struct _pyb_can_obj_t *pyb_can_obj_all[(2)];
struct _pyb_timer_obj_t *pyb_timer_obj_all[(14)];
struct _pyb_uart_obj_t *pyb_stdio_uart;
struct _pyb_uart_obj_t *pyb_uart_obj_all[(6) + (0)];
